############# English navigation ##############

# main menu

[[main]]
name = "home"
url = "/"
weight = 1

#[[main]]
#name = "home"
#url = ""
#weight = 1

[[main]]
name = "categories"
url = "categories/"
weight = 2

[[main]]
name = "about"
url = "about/"
weight = 3



# # dropdown menu
# [[main]]
# name = "Pages"
# weight = 6
# hasChildren = true
#
#   # dropdown item
#   [[main]]
#   parent = "Pages"
#   name = "page 1"
#   url = "/"
#
#   [[main]]
#   parent = "Pages"
#   name = "page 2"
#   url = "/"
