#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `x` with logo_width, example: "100x"
logo_width = "150px"
# logo text will only show when logo is missing.
logo_text = "ultra-cycling.de"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Michael Lihs"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# main sections
mainSections = ["blog"]
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# copyright text
copyright = "Hosted on [GitHub](https://github.com/ultra-cycling/blog/) | Template [GetHugoThemes](https://gethugothemes.com)"
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= "" 

# author
[author_block]
title= "WELCOME TO MY BLOG"
image= "images/author.png"
content= "My name is Michael Lihs. I am a father, I like to ride my bike and I take photos of people, bikes and places every now and then."

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################

[[social]]
icon = "fab fa-twitter"
link = "https://twitter.com/kaktusmimi"

[[social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/michaellihs/"

[[social]]
icon = "fab fa-github"
link = "https://www.github.com/michaellihs"

[[social]]
icon = "fab fa-strava"
link = "https://www.strava.com/athletes/16295226"